---
title: "1_NetworkConstruction"
output: html_document
date: "2024-09-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load data and packages}
#load packages
library(tidyverse); library(scales);library(bipartite);library(ggpubr);library(igraph);library(ergm)

#load data
metadata <- read.csv("~/Documents/Manuscripts/SAVA_Network/Data/Survey_Demographic_Health.csv")
vi <- read.csv("~/Downloads/Volume_Intersection.csv")
animal_dat <- read.csv("~/Documents/Projects/SAVA_multilayer/cleaned_tables/Survey_Animal_Health.csv") %>% rename(id1="animal_id")



```

```{r Construct Networks}
#Identify villages
village <- metadata %>% dplyr::select(social_netid, village) %>% rename(id1= social_netid)

#Organize Edge Data (for each village, create an edgelist of bipartite interactions)
vi_adj <- left_join(vi, village, by = "id1")
vi_adj1 <- vi_adj %>% select(id1, id2, VI_95, village) %>% rename(weight = VI_95)
vi_adj2 <- vi_adj1[!grepl("Z", vi_adj1$id1),]
vi_adj2 <- vi_adj2[!grepl("Z", vi_adj2$id2),]
vi_mand_edge <- vi_adj2 %>% filter(village =="Mandena") %>% select(id1, id2, weight)
vi_sara_edge <- vi_adj2 %>% filter(village =="Sarahandrano") %>% select(id1, id2, weight)
vi_anda_edge <- vi_adj2 %>% filter(village =="Andatsakala"|village=="Ampandrana") %>% select(id1, id2, weight) 
vi_adj3 <- vi_adj1
vi_adj4 <- vi_adj3[grepl("Z", vi_adj3$id1),]
vi_adj4b <- vi_adj4[grepl("Z", vi_adj4$id2),]
village2 <- village %>% rename(social_netid =id1)
vi_adj4c <- left_join(vi_adj4b, animal_dat, by ="id1") %>% select(id1, id2, weight, social_netid)
vi_adj4d <- left_join(vi_adj4c, village2, by = "social_netid") %>% select(-social_netid)
vi_mand_edge_a <- vi_adj4d %>% filter(village =="Mandena") %>% select(id1, id2, weight)
vi_sara_edge_a <- vi_adj4d %>% filter(village =="Sarahandrano") %>% select(id1, id2, weight)
vi_anda_edge_a <- vi_adj4d %>% filter(village =="Andatsakala"|village=="Ampandrana") %>% select(id1, id2, weight)
vi_adj5 <- anti_join(vi_adj1, vi_adj2)
vi_adj6 <- anti_join(vi_adj5, vi_adj4)
vi_adj7 <- vi_adj6[grepl("Z", vi_adj6$id1),]
vi_adj8 <- vi_adj6[grepl("Z", vi_adj6$id2),] 
colnames(vi_adj8) <- c("id2", "id1", "weight", "village")
vi_adj8 <- vi_adj8 %>% select(id1, id2, weight,village)
vi_adj9 <- rbind(vi_adj7, vi_adj8)
vi_adj9$village[vi_adj9$village=="Ampandrana"] <- "Andatsakala"

vi_mand_edge_m <- vi_adj9 %>% filter(village =="Mandena") %>% select(id1, id2, weight)
vi_sara_edge_m <- vi_adj9 %>% filter(village =="Sarahandrano") %>% select(id1, id2, weight)
vi_anda_edge_m <- vi_adj9 %>% filter(village =="Andatsakala") %>% select(id1, id2, weight)

```

```{r}

mean(vi_mand_edge_m$weight)
median(vi_mand_edge_m$weight)
quantile(vi_mand_edge_m$weight, 0.85)


mean(vi_sara_edge_m$weight)
median(vi_sara_edge_m$weight)
quantile(vi_sara_edge_m$weight, 0.85)

mean(na.omit(vi_anda_edge_m$weight))
median(na.omit(vi_anda_edge_m$weight))
quantile(na.omit(vi_anda_edge_m$weight), 0.85)

mean(na.omit(vi_adj9$weight))
median(na.omit(vi_adj9$weight))


vi_mand_edge_m2 <- vi_mand_edge_m %>% mutate(weight = ifelse(weight < 4.7, 0, weight))
vi_sara_edge_m2 <- vi_sara_edge_m %>% mutate(weight = ifelse(weight < 6.25, 0, weight))
vi_anda_edge_m2 <- vi_anda_edge_m %>% mutate(weight = ifelse(weight < 4.22, 0, weight))


vi_mand_edge_m3 <- vi_mand_edge_m %>% mutate(weight = ifelse(weight < 9.593401  , 0, weight))
vi_sara_edge_m3 <- vi_sara_edge_m %>% mutate(weight = ifelse(weight < 13.6283 , 0, weight))
vi_anda_edge_m3 <- vi_anda_edge_m %>% mutate(weight = ifelse(weight < 9.575529  , 0, weight))


vi_mand_edge_m4 <- vi_mand_edge_m %>% mutate(weight = ifelse(weight <2.686435  , 0, weight))
vi_sara_edge_m4 <- vi_sara_edge_m %>% mutate(weight = ifelse(weight < 3.608667  , 0, weight))
vi_anda_edge_m4 <- vi_anda_edge_m %>% mutate(weight = ifelse(weight < 2.247862  , 0, weight))




```

```{r Construct Networks}
#Save edgelists
write.csv(vi_mand_edge_m2, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_mand.csv")
write.csv(vi_sara_edge_m2, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_sara.csv")
write.csv(vi_anda_edge_m2, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_anda.csv")


write.csv(vi_mand_edge_m3, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_mand_5.csv")
write.csv(vi_sara_edge_m3, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_sara_5.csv")
write.csv(vi_anda_edge_m3, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_anda_5.csv")

write.csv(vi_mand_edge_m4, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_mand_15.csv")
write.csv(vi_sara_edge_m4, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_sara_15.csv")
write.csv(vi_anda_edge_m4, "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_anda_15.csv")


vi_mand_edge <- read.csv( "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_mand.csv")

vi_sara_edge <- read.csv( "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_sara.csv")

vi_anda_edge <- read.csv( "~/Documents/GitHub/human_animal_networks/gps_networks/outputs/gps_edge_anda.csv")

vi_mand_edge$Village <- "M"
vi_sara_edge$Village <- "S"
vi_anda_edge$Village <- "A"

edges_total <- rbind(vi_mand_edge, vi_sara_edge, vi_anda_edge)

ggplot(data= edges_total, aes(x=weight, color= Village, fill=Village))+
  geom_density(alpha=0.1)+
  theme_classic()+
  ylab("Density")+
  xlab("Volume Intersection")+
  geom_vline(xintercept = 4.7, linetype= "dashed", color="green")+
  geom_vline(xintercept = 6.25, linetype= "dashed", color="blue")+
  geom_vline(xintercept = 4.22, linetype= "dashed", color="red")


vline_df <- data.frame(
  Village = rep(c("M", "S", "A"), times = 3),
  xintercept = c(9.593401, 13.6283, 9.575529, 4.7, 6.25, 4.22, 2.686435, 3.608667, 2.247862),
  threshold = c("5%", "5%", "5%", "10%", "10%", "10%", "15%", "15%", "15%"),
  line_id = rep(c("M", "S", "A"), times = 3))


ggplot(edges_total, aes(x = weight)) +
  geom_density(aes(color = Village), alpha = 0.1) +
  geom_vline(
    data = vline_df,
    aes(xintercept = xintercept, color = line_id),
    linetype = "dashed"
  ) +
  theme_classic() +
  facet_wrap(~Village)


village_m_plot <- ggplot(edges_total[edges_total$Village=="M",], aes(x = weight)) +
  geom_density( alpha = 0.1) +
  geom_vline(
    data = vline_df[vline_df$line_id=="M",],
    aes(xintercept = xintercept, color = threshold),
    linetype = "dashed"
  ) +
  theme_classic() +
  ylab("Density")+
  xlab("Weight")+
  labs(color = "Threshold Type")


village_a_plot <- ggplot(edges_total[edges_total$Village=="A",], aes(x = weight)) +
  geom_density( alpha = 0.1) +
  geom_vline(
    data = vline_df[vline_df$line_id=="A",],
    aes(xintercept = xintercept, color = threshold),
    linetype = "dashed"
  ) +
  theme_classic() +
  ylab("Density")+
  xlab("Weight")+
  labs(color = "Threshold Type")



village_s_plot <- ggplot(edges_total[edges_total$Village=="S",], aes(x = weight)) +
  geom_density( alpha = 0.1) +
  geom_vline(
    data = vline_df[vline_df$line_id=="S",],
    aes(xintercept = xintercept, color = threshold),
    linetype = "dashed"
  ) +
  theme_classic() +
  ylab("Density")+
  xlab("Weight")+
  labs(color = "Threshold Type")

density_plot <- ggarrange(village_a_plot, village_m_plot, village_s_plot, ncol =1, labels = c("A","M", "S"), common.legend = TRUE)




village_m_plot2 <- ggplot(edges_total[edges_total$Village=="M",], aes(x = weight)) +
  geom_histogram(aes(y = after_stat(density)),  alpha = 0.4) +
  geom_vline(
    data = vline_df[vline_df$line_id=="M",],
    aes(xintercept = xintercept, color = threshold),
    linetype = "dashed"
  ) +
  theme_classic() +
  ylab("Density") +
  xlab("Weight") +
  labs(color = "Threshold Type")


village_a_plot2 <- ggplot(edges_total[edges_total$Village=="A",], aes(x = weight)) +
  geom_histogram(aes(y = after_stat(density)), alpha = 0.4) +
  geom_vline(
    data = vline_df[vline_df$line_id=="A",],
    aes(xintercept = xintercept, color = threshold),
    linetype = "dashed"
  ) +
  theme_classic() +
  ylab("Density") +
  xlab("Weight") +
  labs(color = "Threshold Type")


village_s_plot2 <- ggplot(edges_total[edges_total$Village=="S",], aes(x = weight)) +
  geom_histogram(aes(y = after_stat(density)), alpha = 0.4) +
  geom_vline(
    data = vline_df[vline_df$line_id=="S",],
    aes(xintercept = xintercept, color = threshold),
    linetype = "dashed"
  ) +
  theme_classic() +
  ylab("Density") +
  xlab("Weight") +
  labs(color = "Threshold Type")

hist_plot <- ggarrange(village_a_plot2, village_m_plot2, village_s_plot2,
          ncol = 1, labels = c("A","M","S"), common.legend = TRUE)


ggarrange(density_plot, hist_plot, ncol =2, labels = c("a)", "b)"))



m_hist_zoom <- ggplot(vi_mand_edge_m, aes(x = weight)) +
  geom_histogram(aes(y = after_stat(density)), alpha = 0.4) +
  theme_classic() +
  ylab("Density") +
  xlab("Weight") +
  labs(color = "Threshold Type")+
  xlim(0,1)+
  ylim(0,1.7)

a_hist_zoom <- ggplot(vi_anda_edge_m, aes(x = weight)) +
  geom_histogram(aes(y = after_stat(density)), alpha = 0.4) +
  theme_classic() +
  ylab("Density") +
  xlab("Weight") +
  labs(color = "Threshold Type")+
  xlim(0,1)+
  ylim(0,1.7)

s_hist_zoom <- ggplot(vi_sara_edge_m, aes(x = weight)) +
  geom_histogram(aes(y = after_stat(density)), alpha = 0.4) +
  theme_classic() +
  ylab("Density") +
  xlab("Weight") +
  labs(color = "Threshold Type")+
  xlim(0,1)+
  ylim(0,1.7)


ggarrange(a_hist_zoom, m_hist_zoom, s_hist_zoom, ncol =1, labels = c("A","M", "S"), common.legend = TRUE)

```

