---
title: "2_ERGM"
output: html_document
date: "2024-09-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load packages
library(tidyverse); library(scales);library(bipartite);library(ggpubr);library(ergm);library(network);library(ggnet);library(ergMargins)

#Load data
wd_path <- '~/Documents/GitHub/human_animal_networks/gps_networks/'
getwd()
setwd(wd_path)
data_path <- 'outputs/'

gps_edge_mand <- read.csv(file=paste0(data_path,"/gps_edge_mand.csv")) %>% select(-X)
gps_edge_anda <- read.csv(file=paste0(data_path,"/gps_edge_anda.csv")) %>% select(-X)
gps_edge_sara <- read.csv(file=paste0(data_path,"/gps_edge_sara.csv")) %>% select(-X)

metadata <- read.csv("~/Documents/GitHub/human_animal_networks/gps_networks/metadata2.csv")
animal_dat <- read.csv("~/Documents/Projects/SAVA_multilayer/cleaned_tables/Survey_Animal_Health.csv") %>% rename(id1="animal_id")

metadata$school_level[metadata$school_level=="None"] <- 1
metadata$school_level[metadata$school_level=="Primary"] <- 2
metadata$school_level[metadata$school_level=="Secondary"] <- 3
metadata$school_level[metadata$school_level=="Higher"] <- 4
metadata$school_level <- as.numeric(metadata$school_level)

```

```{r Construct networks}

#Mandena
gps_edge_mand2 <- as.data.frame(gps_edge_mand %>% pivot_wider(names_from = id1, values_from = weight))
rownames(gps_edge_mand2) <- gps_edge_mand2$id2
gps_edge_mand2 <- gps_edge_mand2 %>% select(-id2)
gps_edge_mand3 <- as.matrix(gps_edge_mand2)
gps_edge_mand3[is.na(gps_edge_mand3)] <- 0
net_mand <-network::network(gps_edge_mand3,bipartite=T,matrix.type="bipartite")
plot(net_mand)

gps_edge_mand_binary <- gps_edge_mand3 
gps_edge_mand_binary[gps_edge_mand_binary>0] <- 1
mean(rowSums(gps_edge_mand_binary))

#sarahandrano
gps_edge_sara2 <- as.data.frame(gps_edge_sara %>% pivot_wider(names_from = id1, values_from = weight))
rownames(gps_edge_sara2) <- gps_edge_sara2$id2
gps_edge_sara2 <- gps_edge_sara2 %>% select(-id2)
gps_edge_sara3 <- as.matrix(gps_edge_sara2)
gps_edge_sara3[is.na(gps_edge_sara3)] <- 0
net_sara <-network::network(gps_edge_sara3,bipartite=T,matrix.type="bipartite")
plot(net_sara)

gps_edge_sara_binary <- gps_edge_sara3 
gps_edge_sara_binary[gps_edge_sara_binary>0] <- 1
mean(rowSums(gps_edge_sara_binary))

#Andatsakala
gps_edge_anda2 <- as.data.frame(gps_edge_anda %>% pivot_wider(names_from = id1, values_from = weight))
rownames(gps_edge_anda2) <- gps_edge_anda2$id2
gps_edge_anda2 <- gps_edge_anda2 %>% select(-id2)
gps_edge_anda3 <- as.matrix(gps_edge_anda2)
gps_edge_anda3[is.na(gps_edge_anda3)] <- 0
net_anda <-network::network(gps_edge_anda3,bipartite=T,matrix.type="bipartite")
plot(net_anda)

gps_edge_anda_binary <- gps_edge_anda3 
gps_edge_anda_binary[gps_edge_anda_binary>0] <- 1
mean(rowSums(gps_edge_anda_binary))



```

```{r Assign vertex attributes: Mandena}


metadata_mand <- metadata %>% filter(village=="Mandena")

network.vertex.names(net_mand)
people_names <- as.data.frame(network.vertex.names(net_mand)[1:186])
colnames(people_names) <- "People"
animal_names <- as.data.frame(network.vertex.names(net_mand)[187:257])
colnames(animal_names) <- "Animals"
allnames <- as.data.frame(network.vertex.names(net_mand))
colnames(allnames) <- "Names"

#Mode
type <- c(rep("People", 186), c(rep("Animals", 71)))
names(type) <- net_mand %v% 'vertex_names'
network::set.vertex.attribute(net_mand,"type",type)

#Age
age <- scale(metadata_mand$age)
names(age) <- metadata_mand$social_netid
age <- age[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"age",age)
network::get.vertex.attribute(net_mand,attrname="age")
#missing for #94

#Gender
gender <- metadata_mand$gender
names(gender) <- metadata_mand$social_netid
gender <- gender[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"gender",gender)
network::get.vertex.attribute(net_mand,attrname="gender")

#CGSOL
cgsol <- scale(metadata_mand$commercial_goods)
names(cgsol) <- metadata_mand$social_netid
cgsol <- cgsol[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"cgsol",cgsol)
network::get.vertex.attribute(net_mand,attrname="cgsol")

#HSOL
hsol <- scale(metadata_mand$house_sol)
names(hsol) <- metadata_mand$social_netid
hsol <- hsol[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"hsol",hsol)
network::get.vertex.attribute(net_mand,attrname="hsol")

#Vanilla
vanilla <- metadata_mand$crops_vanilla
names(vanilla) <- metadata_mand$social_netid
vanilla <- vanilla[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"vanilla",vanilla)
network::get.vertex.attribute(net_mand,attrname="vanilla")

#Land Size
land <- scale(metadata_mand$landsize_in_daba)
names(land) <- metadata_mand$social_netid
land <- land[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"land",land)
network::get.vertex.attribute(net_mand,attrname="land")
#Missing #80, 149, 166, 171, 176

#Household size
size <- scale(metadata_mand$household_size)
names(size) <- metadata_mand$social_netid
size <- size[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"size",size)
network::get.vertex.attribute(net_mand,attrname="size")
#Missing #96

#school
school <- scale(metadata_mand$school_level)
names(school) <- metadata_mand$social_netid
school <- school[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"school",school)
network::get.vertex.attribute(net_mand,attrname="school")

#Animal species
species <- animal_dat$species
species[species!="Cow"] <-"NotZebu"
species[species=="Cow"] <-"Zebu"
names(species) <- animal_dat$id1
species <- species[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"species",species)
network::get.vertex.attribute(net_mand,attrname="species")

#Animal sex
sex <- animal_dat$sex
names(sex) <- animal_dat$id1
sex <- sex[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"sex",sex)
network::get.vertex.attribute(net_mand,attrname="sex")

#Animal species
animal_species <- animal_dat$species
names(animal_species) <- animal_dat$id1
animal_species <- animal_species[ net_mand %v% 'vertex.names' ]
network::set.vertex.attribute(net_mand,"animal_species",animal_species)
network::get.vertex.attribute(net_mand,attrname="animal_species")


degree <- sna::degree(net_mand)
network::set.vertex.attribute(net_mand,"degree",degree)
network::get.vertex.attribute(net_mand,attrname="degree")

color <- animal_dat$species
color[color=="Cow"] <- "#E69F00"
color[color=="Pig"] <- "#56B4E9"
color[color=="Cat"] <- "#009E73"
color[color=="Dog"] <- "#F0E442"
color <- c(rep("grey50",179), color)
names(color) <- net_mand %v% 'vertex_names'
network::set.vertex.attribute(net_mand,"color",color)
network::get.vertex.attribute(net_mand,attrname="color")

#Remove nodes that have missing values (3% of nodes)
nodes_to_remove <- c(94, 96, 80, 149, 166, 171, 176)
net_mand <- network::delete.vertices(net_mand, nodes_to_remove)

```

```{r Assign vertex attributes: Sarhandrano}

metadata_sara <- metadata %>% filter(village=="Sarahandrano")

network.vertex.names(net_sara)
people_names <- as.data.frame(network.vertex.names(net_sara)[1:343])
colnames(people_names) <- "People"
animal_names <- as.data.frame(network.vertex.names(net_sara)[344:464])
colnames(animal_names) <- "Animals"
allnames <- as.data.frame(network.vertex.names(net_sara))
colnames(allnames) <- "Names"

#Mode
type <- c(rep("People", 343), c(rep("Animals", 122)))
names(type) <- net_sara %v% 'vertex_names'
network::set.vertex.attribute(net_sara,"type",type)

#Age
age <- scale(metadata_sara$age)
names(age) <- metadata_sara$social_netid
age <- age[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"age",age)
network::get.vertex.attribute(net_sara,attrname="age")
#missing for #270

#Gender
gender <- metadata_sara$gender
names(gender) <- metadata_sara$social_netid
gender <- gender[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"gender",gender)
network::get.vertex.attribute(net_sara,attrname="gender")

#CGSOL
cgsol <- scale(metadata_sara$commercial_goods)
names(cgsol) <- metadata_sara$social_netid
cgsol <- cgsol[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"cgsol",cgsol)
network::get.vertex.attribute(net_sara,attrname="cgsol")

#HSOL
hsol <- scale(metadata_sara$house_sol)
names(hsol) <- metadata_sara$social_netid
hsol <- hsol[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"hsol",hsol)
network::get.vertex.attribute(net_sara,attrname="hsol")

#Vanilla
vanilla <- metadata_sara$crops_vanilla
names(vanilla) <- metadata_sara$social_netid
vanilla <- vanilla[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"vanilla",vanilla)
network::get.vertex.attribute(net_sara,attrname="vanilla")

#Land Size
land <- scale(metadata_sara$landsize_in_daba)
names(land) <- metadata_sara$social_netid
land <- land[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"land",land)
network::get.vertex.attribute(net_sara,attrname="land")
#Missing #11, 74, 179, 190, 202, 205, 243, 251, 305, 330, 331

#Household size
size <- scale(metadata_sara$household_size)
names(size) <- metadata_sara$social_netid
size <- size[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"size",size)
network::get.vertex.attribute(net_sara,attrname="size")

#school
school <- scale(metadata_sara$school_level)
names(school) <- metadata_sara$social_netid
school <- school[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"school",school)
network::get.vertex.attribute(net_sara,attrname="school")
#Missing #11

#Animal species
species <- animal_dat$species
species[species!="Cow"] <-"NotZebu"
species[species=="Cow"] <-"Zebu"
names(species) <- animal_dat$id1
species <- species[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"species",species)
network::get.vertex.attribute(net_sara,attrname="species")

#Animal sex
sex <- animal_dat$sex
names(sex) <- animal_dat$id1
sex <- sex[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"sex",sex)
network::get.vertex.attribute(net_sara,attrname="sex")

#Animal species
animal_species <- animal_dat$species
names(animal_species) <- animal_dat$id1
animal_species <- animal_species[ net_sara %v% 'vertex.names' ]
network::set.vertex.attribute(net_sara,"animal_species",animal_species)
network::get.vertex.attribute(net_sara,attrname="animal_species")

degree <- sna::degree(net_sara)
network::set.vertex.attribute(net_sara,"degree",degree)
network::get.vertex.attribute(net_sara,attrname="degree")

color <- animal_dat$species
color[color=="Cow"] <- "#E69F00"
color[color=="Pig"] <- "#56B4E9"
color[color=="Cat"] <- "#009E73"
color[color=="Dog"] <- "#F0E442"
color <- c(rep("grey50",391), color)
names(color) <- net_sara %v% 'vertex_names'
network::set.vertex.attribute(net_sara,"color",color)
network::get.vertex.attribute(net_sara,attrname="color")

#Remove nodes that have missing values (2.6% of nodes)
nodes_to_remove_sara <- c(270, 11, 74, 179, 190, 202, 205, 243, 251, 305, 330, 331, 463)
net_sara <- network::delete.vertices(net_sara, nodes_to_remove_sara)

#net_sara <- network::delete.vertices(net_sara, 398)

```

```{r Assign vertex attributes: Andatasakala}

metadata_anda <- metadata %>% filter(village=="Andatsakala"| village=="Ampandrana")

network.vertex.names(net_anda)
people_names <- as.data.frame(network.vertex.names(net_anda)[1:416])
colnames(people_names) <- "People"
animal_names <- as.data.frame(network.vertex.names(net_anda)[417:554])
colnames(animal_names) <- "Animals"
allnames <- as.data.frame(network.vertex.names(net_anda))
colnames(allnames) <- "Names"

#Mode
type <- c(rep("People", 416), c(rep("Animals", 138)))
names(type) <- net_anda %v% 'vertex_names'
network::set.vertex.attribute(net_anda,"type",type)

#Age
age <- scale(metadata_anda$age)
names(age) <- metadata_anda$social_netid
age <- age[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"age",age)
network::get.vertex.attribute(net_anda,attrname="age")

#Gender
gender <- metadata_anda$gender
names(gender) <- metadata_anda$social_netid
gender <- gender[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"gender",gender)
network::get.vertex.attribute(net_anda,attrname="gender")

#CGSOL
cgsol <- scale(metadata_anda$commercial_goods)
names(cgsol) <- metadata_anda$social_netid
cgsol <- cgsol[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"cgsol",cgsol)
network::get.vertex.attribute(net_anda,attrname="cgsol")

#HSOL
hsol <- scale(metadata_anda$house_sol)
names(hsol) <- metadata_anda$social_netid
hsol <- hsol[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"hsol",hsol)
network::get.vertex.attribute(net_anda,attrname="hsol")

#Vanilla
vanilla <- metadata_anda$crops_vanilla
names(vanilla) <- metadata_anda$social_netid
vanilla <- vanilla[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"vanilla",vanilla)
network::get.vertex.attribute(net_anda,attrname="vanilla")

#Land Size
land <- scale(metadata_anda$landsize_in_daba)
names(land) <- metadata_anda$social_netid
land <- land[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"land",land)
network::get.vertex.attribute(net_anda,attrname="land")
#Missing #35, 40, 102, 107, 119, 126, 309, 320, 337, 362, 364, 370, 385, 391, 398, 404

#Household size
size <- scale(metadata_anda$household_size)
names(size) <- metadata_anda$social_netid
size <- size[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"size",size)
network::get.vertex.attribute(net_anda,attrname="size")

#school
school <- scale(metadata_anda$school_level)
names(school) <- metadata_anda$social_netid
school <- school[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"school",school)
network::get.vertex.attribute(net_anda,attrname="school")
#Missing #179, 216, 397, 406, 408, 411

#Animal species
species <- animal_dat$species
species[species!="Cow"] <-"NotZebu"
species[species=="Cow"] <-"Zebu"
names(species) <- animal_dat$id1
species <- species[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"species",species)
network::get.vertex.attribute(net_anda,attrname="species")

#Animal sex
sex <- animal_dat$sex
names(sex) <- animal_dat$id1
sex <- sex[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"sex",sex)
network::get.vertex.attribute(net_anda,attrname="sex")

#Animal species
animal_species <- animal_dat$species
names(animal_species) <- animal_dat$id1
animal_species <- animal_species[ net_anda %v% 'vertex.names' ]
network::set.vertex.attribute(net_anda,"animal_species",animal_species)
network::get.vertex.attribute(net_anda,attrname="animal_species")


degree <- sna::degree(net_anda)
network::set.vertex.attribute(net_anda,"degree",degree)
network::get.vertex.attribute(net_anda,attrname="degree")




color <- animal_dat$species
color[color=="Cow"] <- "#E69F00"
color[color=="Pig"] <- "#56B4E9"
color[color=="Cat"] <- "#009E73"
color[color=="Dog"] <- "#F0E442"
color <- c(rep("grey50",391), color)
names(color) <- net_anda %v% 'vertex_names'
network::set.vertex.attribute(net_anda,"color",color)
network::get.vertex.attribute(net_anda,attrname="color")



#Remove nodes that have missing values (5% of nodes)
nodes_to_remove_anda <- c(35, 40, 102, 107, 119, 126, 309, 320, 337, 362, 364, 370, 385, 391, 398, 404, 179, 216, 397, 406, 408, 411, 416)
net_anda <- network::delete.vertices(net_anda, nodes_to_remove_anda)

net_anda <- network::delete.vertices(net_anda, c(371,386))

```

```{r ERGM}
set.seed(123)

ergm_mandena <- ergm(net_mand ~ edges + b1cov("age")+b1factor("gender")+b1factor("vanilla")+
                        b1cov("land")+b1cov("size")+b1cov("school")+
                         b1cov("cgsol")+b1cov("hsol")+b2factor("species")+
                    b1cov("cgsol"):b2factor("species") +b1cov("hsol"):b2factor("species") +
                      b1factor("vanilla"):b2factor("species")+ b2factor("sex")+ b1degree(2)+ b1degree(1)+ b1degree(3), 
                 control = control.ergm(seed = 123))

mandena_summary <-summary(ergm_mandena)
mandena_summary
gof_mandena <- gof(ergm_mandena)
plot(gof_mandena)
max(vif.ergm(ergm_mandena))


ergm_sara <- ergm(net_sara ~ edges + b1cov("age")+b1factor("gender")+b1factor("vanilla")+
                        b1cov("land")+b1cov("size")+b1cov("school")+
                         b1cov("cgsol")+b1cov("hsol")+b2factor("species")+
                    b1cov("cgsol"):b2factor("species") +b1cov("hsol"):b2factor("species") +
                      b1factor("vanilla"):b2factor("species")+ b2factor("sex")+ b1degree(2)+ b1degree(1)+ b1degree(3)+ b1degree(4)+ b1degree(5)+ b1degree(6)+ b1degree(7)+ b1degree(8)+ b1degree(9)+ b1degree(10)+ b1degree(11), 
                 control = control.ergm(seed = 123))

sara_summary <-summary(ergm_sara)
sara_summary
gof_sara <- gof(ergm_sara)
plot(gof_sara)
max(vif.ergm(ergm_sara))


ergm_anda <- ergm(net_anda ~ edges + b1cov("age")+b1factor("gender")+b1factor("vanilla")+
                        b1cov("land")+b1cov("size")+b1cov("school")+
                         b1cov("cgsol")+b1cov("hsol")+b2factor("species")+
                    b1cov("cgsol"):b2factor("species") +b1cov("hsol"):b2factor("species") +
                      b1factor("vanilla"):b2factor("species")+ b2factor("sex")+ b1degree(2)+ b1degree(1)+
                      + b1degree(3)+ b1degree(4)+ b1degree(5)+ b1degree(6)+ b1degree(7)+ b1degree(8)+ b1degree(9)+ b1degree(10)+ b1degree(11)+ b1degree(12)+ b1degree(13)+ b1degree(14)+ b1degree(15)+ b1degree(16)+b1degree(22)+b1degree(23), 
                 control = control.ergm(seed = 123))

anda_summary <-summary(ergm_anda)
anda_summary
gof_anda <- gof(ergm_anda)
plot(gof_anda)
max(vif.ergm(ergm_anda))

```

```{r ERGM}


summary_df <- rbind(as.data.frame(mandena_summary$coefficients)[2:14,], as.data.frame(sara_summary$coefficients)[2:14,], as.data.frame(anda_summary$coefficients)[2:14,])
#summary_df <- summary_df[-42,] #CHANGE THIS

summary_df$Village <- c(rep("Mandena", 13), rep("Sarahandrano", 13), rep("Andatsakala", 13))
summary_df$Variable <- rep(c( "Age", "Gender[Male]", "Vanilla Farmer", "Land Size", "Household Size", "School Level",  "Commercial Goods", "House Materials", "Cattle", "Commercial Goods:Cattle", "House Materials:Cattle", "Vanilla:Cattle", "Animal Sex[Male]"))

summary_df$Variable <- factor(summary_df$Variable, levels = c("Age", "Gender[Male]",  "School Level",  "Household Size", "Land Size","Vanilla Farmer", "Commercial Goods", "House Materials", "Animal Sex[Male]",  "Commercial Goods:Cattle", "House Materials:Cattle", "Vanilla:Cattle", "Cattle"))
summary_df$lower_ci <- summary_df$Estimate - 1.96* summary_df$`Std. Error`
summary_df$upper_ci <- summary_df$Estimate + 1.96* summary_df$`Std. Error`
summary_df$lower_ci_90 <- summary_df$Estimate -qnorm(0.95)* summary_df$`Std. Error`
summary_df$upper_ci_90 <- summary_df$Estimate + qnorm(0.95)* summary_df$`Std. Error`

summary_df_filtered <- summary_df %>% filter(Variable !="Edges", Variable !="Cattle", Variable !="House Materials:Cattle", Variable !="Commercial Goods:Cattle", Variable !="Vanilla:Cattle", Variable !="Degree 1",Variable !="Degree 2",Variable !="Degree 3",Variable !="Degree 4", Variable !="Animal Sex[Male]")


 ggplot(summary_df, aes(x = Estimate, y = Variable, color = Village)) +
  geom_point(position = position_dodge(width = 0.5), size = 3) + 
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci), 
                 height = 0.2, position = position_dodge(width = 0.5)) + 
  theme_classic() + 
  labs(x = "Estimated Effect", y = "Variable", 
       title = NULL) +
  scale_color_manual(values = c("#1f77b4", "#ff7f0e", "#2ca02c")) +
  theme(
    legend.position = "right", 
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12)  
  )+
  geom_vline(xintercept=0, linetype= "dashed")
 
 
 
 
 summary_df_filtered2 <- summary_df_filtered
summary_df_filtered2$Significance <- summary_df_filtered2$`Pr(>|z|)`
summary_df_filtered2$Significance[summary_df_filtered2$`Pr(>|z|)`<0.05] <- "Significant"
summary_df_filtered2$Significance[summary_df_filtered2$`Pr(>|z|)`>=0.1] <- "Not Significant"
summary_df_filtered2$Significance[summary_df_filtered2$`Pr(>|z|)`<0.1&summary_df_filtered2$`Pr(>|z|)`>=0.05] <- "Marginally Significant"

 ggplot(summary_df_filtered2, aes(x = Estimate, y = Variable, color = Village)) +
  geom_point(position = position_dodge(width = 0.5), size = 3) + 
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci), 
                 height = 0.2, position = position_dodge(width = 0.5)) + 
  theme_classic() + 
  labs(x = "Estimated Effect", y = "Variable", 
       title = NULL) +
  scale_color_manual(values = c("#1f77b4", "#ff7f0e", "#2ca02c")) +
  theme(
    legend.position = "right", 
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12)  
  )+
  geom_vline(xintercept=0, linetype= "dashed")
 
fig_2 <-ggplot(summary_df_filtered2, aes(x = Estimate, y = Variable, color = Significance, shape=Village)) + geom_point(position = position_dodge(width = 0.5), size = 3) + 
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci), 
                 height = 0.2, position = position_dodge(width = 0.5)) + 
  theme_classic() + 
  labs(x = "Estimated Effect", y = "Variable", 
       title = NULL) +
  scale_color_manual(values = c( "grey70","#1f77b4")) +
  theme(
    legend.position = "right", 
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12)  
  )+
  geom_vline(xintercept=0, linetype= "dashed")



summary_df_filtered3 <- summary_df %>% filter(Variable =="Cattle"| Variable =="House Materials:Cattle"| Variable =="Commercial Goods:Cattle"| Variable =="Vanilla:Cattle"| Variable =="Animal Sex[Male]")

summary_df_filtered3$Significance <- summary_df_filtered3$`Pr(>|z|)`
summary_df_filtered3$Significance[summary_df_filtered3$`Pr(>|z|)`<0.05] <- "Significant"
summary_df_filtered3$Significance[summary_df_filtered3$`Pr(>|z|)`>=0.1] <- "Not Significant"
summary_df_filtered3$Significance[summary_df_filtered3$`Pr(>|z|)`<0.1&summary_df_filtered3$`Pr(>|z|)`>=0.05] <- "Marginally Significant"
 

fig_3 <-ggplot(summary_df_filtered3, aes(x = Estimate, y = Variable, color = Significance, shape=Village)) + geom_point(position = position_dodge(width = 0.5), size = 3) + 
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci), 
                 height = 0.2, position = position_dodge(width = 0.5)) + 
  theme_classic() + 
  labs(x = "Estimated Effect", y = "Variable", 
       title = NULL) +
  scale_color_manual(values = c("lightblue", "grey70","#1f77b4")) +
  theme(
    legend.position = "right", 
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12)  
  )+
  geom_vline(xintercept=0, linetype= "dashed")


ggarrange(fig_2, fig_3, common.legend = TRUE)



summary_df_filtered2$Village[summary_df_filtered2$Village=="Mandena"] <- "M"
summary_df_filtered2$Village[summary_df_filtered2$Village=="Sarahandrano"] <- "S"
summary_df_filtered2$Village[summary_df_filtered2$Village=="Andatsakala"] <- "A"


people_plot <- ggplot(summary_df_filtered2, aes(x = Estimate, y = Variable, color = Village)) + 
  # Points for estimated effects with dodge position
  geom_point(position = position_dodge(width = 0.5), size = 3) + 
  # 95% CI as thinner linerange
  geom_linerange(
    aes(xmin = lower_ci, xmax = upper_ci),
    position = position_dodge(0.5), linewidth = 0.4
  ) +
  # 90% CI as thicker linerange
  geom_linerange(
    aes(xmin = lower_ci_90, xmax = upper_ci_90),
    position = position_dodge(0.5), linewidth = 1.2
  ) + 
  # Classic theme
  theme_classic() +
  # Labels
  labs(x = "Estimated Effect", y = NULL) + 
  # Colorblind-friendly palette from viridis
  scale_color_viridis_d(option = "D", end = 0.8) +  
  # Theme adjustments
  theme(
    legend.position = "right", 
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12)
  ) +
  # Reference line at zero
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40")


summary_df_filtered3$Village[summary_df_filtered3$Village=="Mandena"] <- "M"
summary_df_filtered3$Village[summary_df_filtered3$Village=="Sarahandrano"] <- "S"
summary_df_filtered3$Village[summary_df_filtered3$Village=="Andatsakala"] <- "A"


animals_plot <- ggplot(summary_df_filtered3, aes(x = Estimate, y = Variable, color = Village)) + 
  # Points for estimated effects with dodge position
  geom_point(position = position_dodge(width = 0.5), size = 3) + 
  # 95% CI as thinner linerange
  geom_linerange(
    aes(xmin = lower_ci, xmax = upper_ci),
    position = position_dodge(0.5), linewidth = 0.4
  ) +
  # 90% CI as thicker linerange
  geom_linerange(
    aes(xmin = lower_ci_90, xmax = upper_ci_90),
    position = position_dodge(0.5), linewidth = 1.2
  ) + 
  # Classic theme
  theme_classic() +
  # Labels
  labs(x = "Estimated Effect", y = NULL) + 
  # Colorblind-friendly palette from viridis
  scale_color_viridis_d(option = "D", end = 0.8) +  
  # Theme adjustments
  theme(
    legend.position = "right", 
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12)
  ) +
  # Reference line at zero
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40")

ggarrange(people_plot, animals_plot, labels = c("a", "b"), common.legend = TRUE)

write.csv(summary_df, "summary_df_spatial.csv")




```

```{r}
library(network)
library(sna)  # For degree calculation

# Set up a 1-row, 3-column layout and remove margins
par(mfrow = c(1, 3), mar = c(2, 0, 2, 0))  # Top margin for labels


# --- Plot net_anda ---
node_colors <- net_anda %v% "color"
node_sizes <- net_anda %v% "degree"
scaled_sizes <- ((node_sizes / max(node_sizes, na.rm = TRUE)) * 3) + 0.5

plot(net_anda, 
     vertex.col = node_colors, 
     vertex.cex = scaled_sizes, 
     edge.col = adjustcolor("grey60", alpha.f = 0.5),
     displayisolates = TRUE)
mtext("A", side = 3, line = 0.5, cex = 1, font = 2)  # Add label above


# --- Plot net_mand ---
node_colors <- net_mand %v% "color"
node_sizes <- net_mand %v% "degree"
scaled_sizes <- ((node_sizes / max(node_sizes, na.rm = TRUE)) * 3) + 0.5

plot(net_mand, 
     vertex.col = node_colors, 
     vertex.cex = scaled_sizes, 
     edge.col = adjustcolor("grey60", alpha.f = 0.5),
     displayisolates = TRUE)
mtext("M", side = 3, line = 0.5, cex = 1, font = 2)  # Add label above

# --- Plot net_sara ---
node_colors <- net_sara %v% "color"
node_sizes <- net_sara %v% "degree"
scaled_sizes <- ((node_sizes / max(node_sizes, na.rm = TRUE)) * 3) + 0.5

plot(net_sara, 
     vertex.col = node_colors, 
     vertex.cex = scaled_sizes, 
     edge.col = adjustcolor("grey60", alpha.f = 0.5),
     displayisolates = TRUE)
mtext("S", side = 3, line = 0.5, cex = 1, font = 2)  # Add label above

```

```{r}
library(network)
library(sna)  # For degree calculation

# Set up a 1-row, 3-column layout and remove margins
par(mfrow = c(1, 3), mar = c(0, 0, 0, 0))

# --- Plot net_mand ---
node_colors <- net_mand %v% "color"
node_sizes <- net_mand %v% "degree"
scaled_sizes <- ((node_sizes / max(node_sizes, na.rm = TRUE)) * 3) + 0.5

plot(net_mand, 
     vertex.col = node_colors, 
     vertex.cex = scaled_sizes, 
     edge.col = adjustcolor("grey60", alpha.f = 0.5),
     displayisolates = TRUE)

# --- Plot net_anda ---
node_colors <- net_anda %v% "color"
node_sizes <- net_anda %v% "degree"
scaled_sizes <- ((node_sizes / max(node_sizes, na.rm = TRUE)) * 3) + 0.5

plot(net_anda, 
     vertex.col = node_colors, 
     vertex.cex = scaled_sizes, 
     edge.col = adjustcolor("grey60", alpha.f = 0.5),
     displayisolates = TRUE)

# --- Plot net_sara ---
node_colors <- net_sara %v% "color"
node_sizes <- net_sara %v% "degree"
scaled_sizes <- ((node_sizes / max(node_sizes, na.rm = TRUE)) * 3) + 0.5

plot(net_sara, 
     vertex.col = node_colors, 
     vertex.cex = scaled_sizes, 
     edge.col = adjustcolor("grey60", alpha.f = 0.5),
     displayisolates = TRUE)

```

```{r}

library(sna)

net_anda

mean((sna::degree(net_anda))[1:331])
sd((sna::degree(net_anda))[1:331])

mean((sna::degree(net_anda))[332:451])
sd((sna::degree(net_anda))[332:451])

num_edges <- network.edgecount(net_anda)  # Number of edges
num_nodes <- network.size(net_anda)       # Number of nodes
max_edges <- (num_nodes * (num_nodes - 1)) / 2  # Max edges for undirected

# Edge density calculation
edge_density <- num_edges / max_edges


plot(net_anda)
```

