---
title: "3_EffectSizePooling"
output: html_document
date: "2024-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Data and Packages}

library(tidyverse);library(metafor);library(ggpubr)

summary_df <- read.csv("~/Documents/GitHub/human_animal_networks/gps_networks/summary_df_spatial.csv")

```

```{r Pool Effect Sizes}


pool_function <- function(variable){
  
model_df <- summary_df %>% select(Estimate, `Std..Error`, Variable, Village) %>% filter(Variable==variable)

metaanalysis_model <- rma(yi = model_df$Estimate,   
         sei = model_df$`Std..Error`, 
         method = "FE")

output <- c(metaanalysis_model$beta , metaanalysis_model$ci.lb, metaanalysis_model$ci.ub, metaanalysis_model$pval, metaanalysis_model$se, nrow(model_df))

return(output)

}

name_age_pr <- pool_function(variable ="Age")
name_sex_pr <- pool_function(variable ="Gender[Male]")
name_vanilla_pr <- pool_function(variable ="Vanilla Farmer")
name_ls_pr <- pool_function(variable ="Land Size")
name_hs_pr <- pool_function(variable ="Household Size")
name_sl_pr <- pool_function(variable ="School Level")
name_cgsol_pr <- pool_function(variable ="CGSOL")
name_hsol_pr <- pool_function(variable ="HSOL")
name_zebu_pr <- pool_function(variable ="Zebu")
name_hsol_zebu_pr <- pool_function(variable ="HSOL:Zebu")
name_vanilla_zebu_pr <- pool_function(variable ="Vanilla:Zebu")
name_cgsol_zebu_pr <- pool_function(variable ="CGSOL:Zebu")
name_animal_sex_pr <- pool_function(variable ="Animal Sex[Male]")


meta_df <- as.data.frame(rbind(name_age_pr,
                               name_sex_pr,
                               name_vanilla_pr,
                               name_ls_pr,
                               name_hs_pr,
                               name_sl_pr,
                               name_cgsol_pr,
                               name_hsol_pr,
                               name_zebu_pr,
                               name_hsol_zebu_pr,
                               name_vanilla_zebu_pr,
                               name_cgsol_zebu_pr,
                               name_animal_sex_pr))


colnames(meta_df) <- c("Estimate", "Lower", "Upper", "Pr(>|z|)","SE", "N")

meta_df$Variable <- c("Age", "Gender[Man]", "Vanilla Farmer", "Land Size", "Household Size", "School Level",  "CGSOL", "HSOL", "Cattle", "HSOL:Cattle", "Vanilla:Cattle", "CGSOL:Cattle", "Animal Sex[Male]")



meta_df$lower_ci <- meta_df$Estimate - 1.96 * meta_df$SE
meta_df$upper_ci <- meta_df$Estimate + 1.96 * meta_df$SE

meta_df$lower_ci_90 <- meta_df$Estimate - qnorm(0.95) * meta_df$SE
meta_df$upper_ci_90 <- meta_df$Estimate + qnorm(0.95) * meta_df$SE



```

```{r Plot}

meta_df_filtered <- meta_df %>% filter(Variable !="Edges", Variable !="Cattle", Variable !="HSOL:Cattle", Variable !="CGSOL:Cattle", Variable !="Vanilla:Cattle", Variable !="Degree 1",Variable !="Degree 2",Variable !="Degree 3",Variable !="Degree 4", Variable !="Animal Sex[Male]")

meta_df_filtered$Variable <- factor(meta_df_filtered$Variable, levels = c("Age", "Gender[Man]", "School Level", "Household Size", "Land Size", "Vanilla Farmer", "CGSOL", "HSOL"))

people_plot_pooled <- ggplot(meta_df_filtered, aes(x = Estimate, y = Variable)) + 
  # Points for estimated effects with dodge position
  geom_point(position = position_dodge(width = 0.5), size = 3) + 
  # 95% CI as thinner linerange
  geom_linerange(
    aes(xmin = lower_ci, xmax = upper_ci),
    position = position_dodge(0.5), linewidth = 0.4
  ) +
  # 90% CI as thicker linerange
  geom_linerange(
    aes(xmin = lower_ci_90, xmax = upper_ci_90),
    position = position_dodge(0.5), linewidth = 1.2
  ) + 
  # Classic theme
  theme_classic() +
  # Labels
  labs(x = "Estimated Effect", y = NULL) + 
  # Theme adjustments
  theme(
    legend.position = "right", 
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12)
  ) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40")


meta_df_filtered2 <- meta_df %>% filter(Variable =="Cattle"| Variable =="HSOL:Cattle"| Variable =="CGSOL:Cattle"| Variable =="Vanilla:Cattle"| Variable =="Animal Sex[Male]")
meta_df_filtered2$Variable <- factor(meta_df_filtered2$Variable, levels = c("Animal Sex[Male]", "CGSOL:Cattle", "HSOL:Cattle", "Vanilla:Cattle", "Cattle"))

animals_plot_pooled <- ggplot(meta_df_filtered2, aes(x = Estimate, y = Variable)) + 
  # Points for estimated effects with dodge position
  geom_point(position = position_dodge(width = 0.5), size = 3) + 
  # 95% CI as thinner linerange
  geom_linerange(
    aes(xmin = lower_ci, xmax = upper_ci),
    position = position_dodge(0.5), linewidth = 0.4
  ) +
  # 90% CI as thicker linerange
  geom_linerange(
    aes(xmin = lower_ci_90, xmax = upper_ci_90),
    position = position_dodge(0.5), linewidth = 1.2
  ) + 
  # Classic theme
  theme_classic() +
  # Labels
  labs(x = "Estimated Effect", y = NULL) + 
  # Colorblind-friendly palette from viridis
  scale_color_viridis_d(option = "D", end = 0.8) +  
  # Theme adjustments
  theme(
    legend.position = "right", 
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12)
  ) +
  # Reference line at zero
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40")

ggarrange(people_plot_pooled, animals_plot_pooled, labels = c("a", "b"), common.legend = TRUE)


```


